### ISSUE TITLE
Add easy , medium , hard  level to our pong game.

### ISSUE THREAD

**Issue by pranavbharadwaj007** [Hacktoberfest-SCE/Lets-Build#45]
project link: https://github.com/Hacktoberfest-SCE/Lets-Build/tree/main/web-dev/pong

**Comment by andrefpoliveira** [comment]
Hey can I work on this?

**Comment by pranavbharadwaj007** [comment]
@andrefpoliveira  https://github.com/Hacktoberfest-SCE/Lets-Build/tree/main/web-dev/pong run the code. try to add new features to the game
